import type { Metadata } from 'next'
import { Barlow } from 'next/font/google'

import './globals.css'
import Footer from '@/components/Footer'

const barlow = Barlow({
  subsets: ['latin'],
  variable: '--font-barlow',
  display: 'swap',
  weight: ['400', '500', '600', '700', '900']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt">
      <body className={`${barlow.variable} antialiased`}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
